### ISSUE TITLE
(URGENT) Image paths for module documents wrong

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#104]
**UPDATED**

Image paths for module documents are wrongly migrated.

e.g.
`documents/modules/associative_text/sections/04-info_reqs.adoc`

stepmod2mn now generates this:

```patch
 [[figure4]]
 .Text appearance and rotation
-image::../../../../iso-10303-stepmod-wg12/data/modules/associative_text/text_appearance_and_rotation.gif[Text appearance and rotation]
+image::../../../iso-10303-stepmod-wg12/data/modules/associative_text/text_appearance_and_rotation.gif[Text appearance and rotation]

```

This should be:
```patch
 [[figure4]]
 .Text appearance and rotation
-image::../../../../iso-10303-stepmod-wg12/data/modules/associative_text/text_appearance_and_rotation.gif[Text appearance and rotation]
+image::../../../documents/associative_text/text_appearance_and_rotation.gif[Text appearance and rotation]
```

**Comment by ronaldtse** [comment]
@Intelligent2013 sorry there was a mistake in the original issue. I wanted the path to NOT have iso-10303-stepmod-wg12, but either migrated to:
* `{documents-path}/{document-name}` or
* `{schema-path}/{schema-name}`

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.26.
