### ISSUE TITLE
(URGENT) SVG diagrams for module documents now missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#106]
The `activity` module under `iso-10303-stepmod-wg12/data/modules/activity` contains a number of graphic files.

<img width="301" alt="Screenshot 2023-12-04 at 12 24 12 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/d6a1a13a-77a3-4328-bd5f-e70cc90bb21e">

After migration to `iso-10303-srl`, the `schemas/activity` directory only contains these files. 

<img width="274" alt="Screenshot 2023-12-04 at 12 24 53 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/f87e3251-0eaf-428c-b0a7-4fdd0adcd64a">

The generated SVG files (e.g. `armexpg1.svg`, `armexpg2.svg`...) are all missing.

These files are meant for the `schemas` output directory, not `documents`, because the image files are referenced within `activity/arm.exp` and `activity/mim.exp`, which are both part of the `schemas` directory.

The command to run is:
1. Go to the `iso-10303-srl` repository (and pull submodules)
2. Run:
```sh
$ bundle exec stepmod-srl-migrate --srl-schemas-dir schemas --srl-docs-dir documents --stepmod-dir iso-10303-stepmod-wg12
```

The relevant underlying command is:
```sh
java -Xss5m -jar #{stepmod2mn_path} #{stepmod_dir} --output #{srl_output_docs_dir}
```

Notice that those files are not generated.

**Comment by Intelligent2013** [comment]
I've confused.
- `activity` is the document in `iso-10303-stepmod-wg12\data\modules\activity`, not the schema
- `iso-10303-stepmod-wg12\data\modules\activity\module.xml` doesn't contain the references to any schemas (no elements `<schema ...`)
- `java -Xss5m -jar stepmod2mn-1.25.jar D:\Work\Metanorma\repositories\iso-10303-srl\iso-10303-stepmod-wg12\data\modules\activity\module.xml  --output D:\Work\Metanorma\repositories\iso-10303-srl\documents` gives the result:
  - in the folder `iso-10303-srl\documents\modules\activity`
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/f77a75e2-6934-4205-9ace-6a8a3732d419)
 - `iso-10303-srl\documents\modules\activity\sections\93-arm-express-g.adoc` contains the correct links to the images
```adoc
image::armexpg1.svg[]
...
image::armexpg2.svg[]
```
 - `iso-10303-srl\documents\modules\activity\sections\94-mim-express-g.adoc` contains the correct links to the images
```adoc
image::mimexpg1.svg[]
...
image::mimexpg2.svg[]
```

  - the folder `iso-10303-srl\schemas` is empty

I think preliminary that there is the issue in `stepmod-utils`.

Currently, I can't run `bundle exec stepmod-srl-migrate --srl-schemas-dir schemas --srl-docs-dir documents --stepmod-dir iso-10303-stepmod-wg12` due the issue https://github.com/metanorma/stepmod-utils/issues/211

**Comment by ronaldtse** [comment]
> iso-10303-stepmod-wg12\data\modules\activity

This directory provides BOTH the schema (`*.exp`) and the document (`module.xml`).

> iso-10303-stepmod-wg12\data\modules\activity\module.xml doesn't contain the references to any schemas (no elements `<schema` ...)

This is because a "data/module" document has a different structure from a "data/resource_docs" document.

"arm" and "mim" means: Application Resource Module and Module Interfacing Module. Both are names that refer to types of EXPRESS schemas.

> iso-10303-srl\documents\modules\activity\sections\93-arm-express-g.adoc contains the correct links to the images

```
image::armexpg1.svg[]
...
image::armexpg2.svg[]
```

Actually, these files are supposed to be in `schemas/activity/`. Inside `schemas/activity/`, there are `arm.exp` and `mim.exp` files.

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.28.
