### ISSUE TITLE
Replace 04-schemas.adoc with a shared template that has specified content in the `templates/` dir

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#114]
As per https://github.com/metanorma/iso-10303-srl/pull/7

We need to do this for all documents. It would be better if we can just share the same file, such as like this:
* https://github.com/metanorma/iso-10303-detached-docs/tree/main/documents/common-files
<img width="925" alt="Screenshot 2023-12-07 at 3 58 30 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/9903e6a0-599c-4f35-aea9-ed34f4b66ac5">

**Comment by Intelligent2013** [comment]
update `stepmod2mn`:
- [ ] replace `04-schemas.adoc` in the .jar resources:
```adoc
[lutaml_express, schemas, repo, leveloffset=+1]
---
include::templates/_schemas.liquid[]
```
- [ ] create symbolic link to the folder `iso-10303-srl/templates`

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.27.
