### ISSUE TITLE
Update schemas directory and related references to separate `schemas/modules` and `schemas/resources`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#118]
As per https://github.com/metanorma/iso-10303-srl/issues/2 

Currently we have:

```
schemas/
|__ action_schema
|__ activity
|__ ...
```

But we now want:
```
schemas/
|__ resources/
     |__ action_schema
     |__ ...
|__ modules/
     |__ activity
     |__ ...
```

**Comment by ronaldtse** [comment]
The consequence of this is that all paths that refer to `schemas/...` need to be updated, including:

* schemas.yaml
* express-g-diagrams.yaml

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.28.
