### ISSUE TITLE
stepmod2mn is deleting schemas.adoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#126]
Currently compilation relies on iso-10303-srl/templates/04-schemas.adoc

When  I generate a collection directory,

`java -Xss5m -jar $STEPMOD2MN iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/$f/publication_index.xml --output iso-10303-srl/$f`

stepmod2mn iterates through the files in the publication_index.xml, and generates subdirectories for each in the output directory.

After the first such folder is generated, iso-10303-srl/templates/04-schemas.adoc becomes an empty document. As a result, compilation of schemas no longer happens.

To reproduce:

Put the attached publication_index.xml in iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_TEST_00041-00045

[publication_index.xml.zip](https://github.com/metanorma/stepmod2mn/files/13673003/publication_index.xml.zip)

Run 

java -Xss5m -jar $STEPMOD2MN iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_TEST_00041-00045/publication_index.xml --output iso-10303-srl/CR_TEST_00041-00045

You will see that stepmod2mn generates SVG files for each of the documents, ISO 10303-41 through ISO 10303-45, in iso-10303-srl/CR_TEST_00041-00045

After it finishes generating the SVG files for ISO 10303-41, and starts on ISO 10303-42, iso-10303-srl/templates/04-schemas.adoc is emptied.

**Comment by Intelligent2013** [comment]
Sorry, my fault.
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.31.
