### ISSUE TITLE
(VERY URGENT) document generation completely broken in 1.32

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#130]
In stepmod-utils there is a flow that uses stepmod2mn to:
1. Generate SVG files
2. Generate documents

This was still working at 1.29. However, the latest 1.32 breaks step 2 completely with no possibility to fix in command-line arguments.

Here's the code:
https://github.com/metanorma/stepmod-utils/blob/915337aedbdb0ce588f3763a68072bcf02e4e071/exe/stepmod-srl-migrate#L149-L162

Basically, step 1 is:
```
java -Xss5m -jar stepmod.jar #{stepmod_dir} --output-documents documents --output-schemas schemas --svgs
```

Which generates all SVGs.

Then step 2:
```
java -Xss5m -jar stepmod.jar #{stepmod_dir} --output-documents documents --output-schemas schemas
```

That generates documents + copies over schemas.

The command at Step 2 is has now completely disappeared from stepmod2mn. This is seen in the HELP of stepmod2mn, it must be used with the `--svg` option.

What stepmod2mn provides instead is this:

```
java -Xss5m -jar #{stepmod2mn_path} #{stepmod_dir} --output #{srl_output_docs_dir}
```

Which is broken (and actually useless) because it also generates SVG files in the output folder, but it only accepts 1 output directory -- we need to separate `documents/` and `schemas/` directories.

**Comment by ronaldtse** [comment]
Hmm... maybe it can work, let me verify.

**Comment by Intelligent2013** [comment]
@ronaldtse I've added the  separate output parameters `--output-documents` and `--output-schemas` for 'SVG generation mode' only. I didn't touch the 'documents generation mode' with one parameter `--output`. Ok, I'll add both `--output-documents` `--output-schemas` for documents generation mode also.

**Comment by Intelligent2013** [comment]
`stepmod2mn` updated in https://github.com/metanorma/stepmod2mn/releases/tag/v1.33.
Now the command
```
bundle exec stepmod-srl-migrate --stepmod2mn-path stepmod2mn-1.33.jar --srl-schemas-dir schemas --srl-docs-dir documents --stepmod-dir iso-10303-stepmod-wg12
```
generates 627 documents in the`documents` folder.
