### ISSUE TITLE
XSL `sect_6_refdata.xsl`: For `module.xml`, some have `<refdata>` that needs to be converted into Clause 6

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#142]
There are only 3 files with `<refdata>`:
<img width="1392" alt="Screenshot 2024-04-04 at 21 46 10" src="https://github.com/metanorma/stepmod2mn/assets/11865/be6e1bb7-369e-47ba-9f8b-e5b71d4a66b7">

The template content is provided here:
<img width="1424" alt="Screenshot 2024-04-04 at 11 54 58" src="https://github.com/metanorma/stepmod2mn/assets/11865/3cb6d5c7-60b5-4dd8-a32a-2e40c7f1b4ea">

If there is `<refdata>` convert clause 6 to:
```adoc
[[refdata]]
== Module reference data

include::../../../templates/module_refdata.adoc[]

{content of <refdata>}
```

NOTE: The file has been added in metanorma/iso-10303-templates@33219a7.

If there is no `<refdata>`:
```adoc
[[refdata]]
== Module reference data

An Application module reference data has not been provided.
```

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.39.
