### ISSUE TITLE
XSL `sect_f_guide.xsl`: `module.xml` support `<usage_guide>` element as Annex F

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#143]
The template is from `iso-10303-stepmod-wg12/xsl/sect_f_guide.xsl`: (this is Annex F)

<img width="1392" alt="Screenshot 2024-04-04 at 21 49 14" src="https://github.com/metanorma/stepmod2mn/assets/11865/d94e1c04-6725-4805-92bc-8458a30f0051">

The files are as follows:
<img width="1424" alt="Screenshot 2024-04-04 at 11 56 57" src="https://github.com/metanorma/stepmod2mn/assets/11865/b498a20f-2e5a-4af7-93f7-43dd0949e161">

When there is `usage_guide`:

```adoc
== Application module implementation and usage guide

{content of usage_guide}
```

When not:
```adoc
== Application module implementation and usage guide

An Application module implementation and usage guide has not been provided.
```

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.39.
