### ISSUE TITLE
Review XSL templates to ensure completeness in "resource" documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#145]
* [x] XSL `res_doc/sect_1_scope.xsl` review
* [x] XSL `res_doc/sect_2_refs.xsl` review
* [x] XSL `res_doc/sect_3_defs.xsl` review
* [x] XSL `res_doc/sect_4_express.xsl` review
* [x] XSL `res_doc/sect_a_short_names.xsl` review
* [x] XSL `res_doc/sect_abstract.xsl` review
* [x] XSL `res_doc/sect_add_scope.xsl` review
* [x] XSL `res_doc/sect_b_obj_reg.xsl` review
* [x] XSL `res_doc/sect_biblio.xsl` review
* [x] XSL `res_doc/sect_c_exp.xsl` review
* [x] XSL `res_doc/sect_c_exp_schema.xsl` review
* [x] XSL `res_doc/sect_contents.xsl` review
* [x] XSL `res_doc/sect_cover.xsl` review
* [x] XSL `res_doc/sect_d_expg.xsl` review
* [x] XSL `res_doc/sect_examples.xsl` review
* [x] XSL `res_doc/sect_foreword.xsl` review
* [x] XSL `res_doc/sect_g_change.xsl` review
* [x] XSL `res_doc/sect_introduction.xsl` review
* [x] XSL `res_doc/sect_introduction_schema_diagexpg.xsl` review
* [x] XSL `res_doc/sect_isocover.xsl` review
* [x] XSL `res_doc/sect_main.xsl` review
* [x] XSL `res_doc/sect_resdocindex.xsl` review
* [x] XSL `res_doc/sect_schema.xsl` review
* [x] XSL `res_doc/sect_tech_discussion.xsl` review
* [x] XSL `res_doc/resource.xsl` review

**Comment by Intelligent2013** [comment]
@ronaldtse when I've started the development of `stepmod2mn`, I get the XSLTs from the repository `iso-10303-stepmod-master` (I don't remember the url). The version of `resource.xsl` (for instance) is:
```
$Id: resource.xsl,v 1.115 2018/08/23 11:13:35 mike Exp $
```

The version from the `iso-10303-stepmod-wg12` (branch `1004503016`) is:
```
$Id: resource.xsl,v 1.120 2020/08/23 18:17:28 tom Exp $
```

There are the differences between the versions. For instance, in the Foreword text (left pane - current xslt, right pane from iso-10303-stepmod-wg12):

![image](https://github.com/metanorma/stepmod2mn/assets/5559926/e741194b-ae6c-4bd3-bfe9-0fe3cde98403)

I see two preliminary tasks for this issue:
- [ ] find the latest original XSLTs (for HTML generation) for iso-10303-stepmod - @ronaldtse could you point me where is the _latest_ versions?
- [ ] merge the differences into the `stepmod2mn` XSLTs.

**Comment by ronaldtse** [comment]
@Intelligent2013 let's use the `develop` branch right now from iso-10303-stepmod-wg12 as the most current. @TrThurman is currently working on a new branch but we don't have that information yet.

**Comment by TRThurman** [comment]
I assume you mean
wg12-stepdev
Branch develop,
on ISO bitbucket.
Please confirm.
Data on develop may not be 100% correct, but should not be malformed.

**Comment by ronaldtse** [comment]
> I assume you mean wg12-stepdev Branch develop, on ISO bitbucket. Please confirm. Data on develop may not be 100% correct, but should not be malformed.

In our team, we only have access to our GitHub repositories. The ISO BitBucket `wg12-stepdev` is mirrored to [`iso-10303-stepmod-wg12`](https://github.com/metanorma/iso-10303-stepmod-wg12).

@TRThurman once you have the new stable branch we will switch to it.

**Comment by TRThurman** [comment]
@ronaldtse, can you change the name of the internal repo to replace the string 'stepmod' with 'stepdev'. The term is unfortunate as wg12-stepmod is legacy and will be confusing to new readers/reviewers.

@ronaldtse Here is the controlling Jira issue for the new branch off 
wg12-stepdev
develop.
https://sd.iso.org/jira-pilot/browse/TCSC410303-2256
Here is the branch:

https://sd.iso.org/bitbucket-pilot/projects/ISOTC184SC4/repos/wg12-stepdev/commits?until=refs%2Fheads%2FTCSC410303-2256-wg12-stepdev_branch_for_srldev

**Comment by Intelligent2013** [comment]
> * res_doc/sect_3_defs.xsl

Note: the sub-clause title `3.1 Terms and definitions` isn't created due the update in https://github.com/metanorma/stepmod2mn/issues/22 (see `2. Section Terms, definitions and abbreviated terms`)

**Comment by Intelligent2013** [comment]
The first sentence in the clause `3.1 Terms and definitions` is:
> For the purposes of this document, the terms and definitions given in ISO 10303-2 1) apply.

therefore this boilerplate should be added:
```
[.boilerplate]
--
For the purposes of this document, the terms and definitions given
in ISO 10303-2 footnote:[Under preparation. Stage at time of publication: ISO/FDIS 10303-2:2023] apply.

ISO and IEC maintain terminology databases for use in standardization
at the following addresses:

* ISO Online browsing platform: available at https://www.iso.org/obp;
 
* IEC Electropedia: available at https://www.electropedia.org/.     
--
```

**Comment by TRThurman** [comment]
ISO 1303-2 is published so no footnote neededOn Apr 22, 2024, at 5:10 AM, Ronald Tse ***@***.***> wrote:﻿

For the purposes of this document, the terms and definitions given in ISO 10303-2 1) apply.

@Intelligent2013 the correct encoding is this:
[source=ISO_10303_2]
== Terms and definitions
Where ISO_10303_2 is the bibliographic anchor of ISO 10303-2.

**Comment by Intelligent2013** [comment]
For adoc:
```

[[defns]]
== Terms, definitions and abbreviated terms

[[termsdefns]]
[source=ISO_10303_2]
=== Terms and definitions

[[abbrv]]
=== Abbreviated terms

For the purposes of this document, the following abbreviated terms apply:

URL:: uniform resource locator
DAG:: Directed Acyclic Graph
pos:: person organization schema
SI:: International System of Units

```
the presentation XML contains `No terms and definitions are listed in this document.` in the top clause `Terms, definitions and abbreviated terms`, but `3.1 Terms and definitions` is empty:
```xml
<terms id="defns" obligation="normative" displayorder="7">
	<title depth="1">3<tab/>Terms, definitions and abbreviated terms</title>
	<p id="_">No terms and definitions are listed in this document.</p>
	<p id="_">ISO and IEC maintain terminology databases for use in
standardization at the following addresses:</p>
	<ul id="_">
		<li>
			<p id="_">ISO Online browsing platform: available at
  <link target="https://www.iso.org/obp"/>
			</p>
		</li>
		<li>
			<p id="_">IEC Electropedia: available at
<link target="https://www.electropedia.org"/>
			</p>
		</li>
	</ul>
	<clause id="termsdefns" inline-header="false" obligation="normative">
		<title depth="2">3.1<tab/>Terms and definitions</title>
	</clause>
	<definitions id="abbrv" type="abbreviated_terms" obligation="normative">
		<title depth="2">3.2<tab/>Abbreviated terms</title>
		<p id="_c1241458-41f8-1e9c-e073-8e5c2bab26d0">For the purposes of this document, the following abbreviated terms apply:</p>
		<dl id="_4e8006fa-f8cc-eeab-c3ef-cb8514596480">
			<dt id="symbol-DAG">DAG</dt>
			<dd>
				<p id="_3779fd10-3ab6-a1cb-a6d9-6c83e1377dcd">Directed Acyclic Graph</p>
			</dd>
...
```

The expected result (render in HTML):
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/c4f0d23d-0242-4c62-94de-eb6cf0df5ca7)

I need to choose the another markup...

**Comment by Intelligent2013** [comment]
The attribute `[source=ISO_10303_2]` should be moved up.

![image](https://github.com/metanorma/stepmod2mn/assets/5559926/21bcb6bc-dd17-4755-b667-f5790013042c)


For adoc:
```adoc

[[defns]]
[source=ISO_10303_2]
== Terms, definitions and abbreviated terms

[[termsdefns]]
=== Terms and definitions

[[abbrv]]
=== Abbreviated terms

For the purposes of this document, the following abbreviated terms apply:

URL:: uniform resource locator
DAG:: Directed Acyclic Graph
pos:: person organization schema
SI:: International System of Units
```
The presentation XML contains correct phrase, but for the top clause:
```xml
<terms displayorder="7" id="defns" obligation="normative">
	<title depth="1">3
            <tab/>Terms, definitions and abbreviated terms</title>
	<p id="_">For the purposes of this document, the terms and definitions given in 
            <xref target="ISO_10303_2">ISO&#160;10303-2</xref>apply.</p>
	<p id="_">ISO and IEC maintain terminology databases for use in standardization at the following addresses:</p>
	<ul id="_">
		<li>
			<p id="_">ISO Online browsing platform: available at 
                    <link target="https://www.iso.org/obp"/>
			</p>
		</li>
		<li>
			<p id="_">IEC Electropedia: available at 
                    <link target="https://www.electropedia.org"/>
			</p>
		</li>
	</ul>
	<clause id="termsdefns" inline-header="false" obligation="normative">
		<title depth="2">3.1
                <tab/>Terms and definitions</title>
	</clause>
	<definitions id="abbrv" obligation="normative" type="abbreviated_terms">
		<title depth="2">3.2
                <tab/>Abbreviated terms</title>
		<p id="_">For the purposes of this document, the following abbreviated terms apply:</p>
		<dl id="_">
			<dt id="symbol-DAG">DAG</dt>
			<dd>
				<p id="_">Directed Acyclic Graph</p>
			</dd>
...
```

**Comment by Intelligent2013** [comment]
> `res_doc/sect_3_defs.xsl`

Note: the `03-terms.adoc` doesn't contain these sub-clauses anymore:
- `=== Terms defined in ISO 8601`
- `=== Terms defined in ISO 10303-1`
- `=== Terms defined in ISO 10303-44`
- `=== Other terms and definitions`

It contains the `=== Terms and definitions` (empty) and `=== Abbreviated terms` only.

**Comment by Intelligent2013** [comment]
> * res_doc/sect_4_express.xsl

Note: the most code isn't using, replaced by template from `templates/resources/schemas.adoc`

**Comment by TRThurman** [comment]
@Intelligent2013 @ronaldtse, This seems to have gone off the rails somewhere.
To clarify: ONLY if the clause 3 contains ONLY terms defined in ISO 10303 is the boilerplate 'see ISO 10303-2 etc., whatever that specific wording is'.

IF a specific resource or module clause 3 contains terms defined by OTHER THAN ISO 10303, those terms shall remain in that clause 3 and some boilerplate referring to ISO 10303-2 should also appear using whatever format etc. is required...

**Comment by Intelligent2013** [comment]
>  - `res_doc/sect_foreword.xsl`

`sect_foreword.xsl` contains `<xsl:apply-templates select="." mode="foreword"/>` only, It's not using in `stepmod2mn`'. `<xsl:apply-templates select="." mode="foreword"/>` is called from `stepmod2mn.resource.adoc.xsl` directly.

**Comment by TRThurman** [comment]
To repeat from earlier comment:
"@Intelligent2013 @ronaldtse, This seems to have gone off the rails somewhere.
To clarify: ONLY if the clause 3 contains ONLY terms defined in ISO 10303 is the boilerplate 'see ISO 10303-2 etc., whatever that specific wording is'.

IF a specific resource or module clause 3 contains terms defined by OTHER THAN ISO 10303, those terms shall remain in that clause 3 and some boilerplate referring to ISO 10303-2 should also appear using whatever format etc. is required..."

@ronaldtse,
We can't remove all the "terms defined in clauses" where the document cited is other than ISO 10303-x

**Comment by Intelligent2013** [comment]
> * res_doc/sect_c_exp.xsl

`sect_c_exp.xsl` isn't using in `stepmod2mn`, it contains `<xsl:apply-templates select="." mode="annexc"/>` only. The template `<xsl:apply-templates select="." mode="annexc"/>` calls directly in `stepmod2mn.resource.adoc.xsl`.

**Comment by Intelligent2013** [comment]
> * res_doc/sect_c_exp_schema.xsl

`sect_c_exp_schema.xsl` isn't using in `stepmod2mn`. `sect_c_exp_schema.xsl` generates express schemas, but `stepmod-utils` generates `.exp` files now.

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_contents.xsl`

`res_doc/sect_contents.xsl` is using for HTML ToC generation. No need to include it into `stepmod2mn`.

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_cover.xsl`

`res_doc/sect_cover.xsl` is using for HTML cover page:

![image](https://github.com/metanorma/stepmod2mn/assets/5559926/cdae8719-a630-4017-b40e-d6d85641ac38)


In `stepmod2mn` the main `document.adoc` generates by the XSLT `stepmod2mn.resource.adoc.xsl`.

Need update:
- [ ] change from `:tc-docnumber: 10681` to `:tc-docnumber: ISO/TC 184/SC 4/WG 12 N10681`
(see https://www.metanorma.org/author/iso/ref/document-attributes/#distribution-group)
- [ ] add `:supersedes: ISO/TC 184/SC 4/WG 12 N10446`
(see https://www.metanorma.org/author/iso/ref/document-attributes/#document-relations)
- [ ] add tests from `<xsl:template match="resource" mode="coverpage">`:
```xml
<xsl:variable name="test_wg_number_supersedes">
      <xsl:call-template name="test_wg_number">
                             <xsl:with-param name="wgnumber"
                                select="./@wg.number.supersedes" />
        </xsl:call-template>
</xsl:variable>
```

@ronaldtse do we need to keep 'Comments to reader', 'Project leader info', 'Project author info' into the document attributes?
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/18d25829-2867-4972-9760-060e56e84354)

like this:
```
:semantic-metadata-comments-to-reader: This document has been reviewed using the internal review ...
:semantic-metadata-project-leader-name:  Max Ungerer
:semantic-metadata-project-leader-address:  PROSTEP AG +
Dolivostraße 11 +
Darmstadt +
64293 +
Germany
:semantic-metadata-project-leader-email: Max.Ungerer@PROSTEP.com
:semantic-metadata-project-editor-name:  Darla Nettles Edwards
:semantic-metadata-project-editor-address: Liberty Business Associates. +
3509 Iron Horse Road +
Ladson +
SC +
29456 +
USA
:semantic-metadata-project-editor-phone: +843-819-3263
:semantic-metadata-project-editor-email: Max.Ungerer@PROSTEP.com
```

**Comment by ronaldtse** [comment]
> do we need to keep 'Comments to reader', 'Project leader info', 'Project author info' into the document attributes?

Yes if possible. That would be good. Thanks!

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_introduction_schema_diagexpg.xsl`

Note: this XSL is using in `data\resource_docs\nutty_bolts\sys\introduction_schema_diagexpg.xml` only.

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_isocover.xsl`

To do: ddd document attribute into `document.adoc`:
- [ ] `:revises: ISO 10303-',@part,':',@previous.revision.year,')`

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_main.xsl`

`sect_main.xsl` is using for the rendering of whole document on the  one html page. No need to include it into `stepmod2mn.xsl`

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_resdocindex.xsl`

`sect_resdocindex.xsl` is using for Index generation:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/8f13501e-235a-4f2f-a713-28305bc4f1b9)
Index generates automatically by Metanorma (by `(((...)))` markup), so no need to include it into `stepmod2mn`.

**Comment by Intelligent2013** [comment]
> * `res_doc/sect_schema.xsl`

Note: `sect_schema.xsl` was used earlier for Section 4, 5, ... (schemas) generation. It replaced by the template `templates/resources/schemas.adoc`. But need to keep `sect_schema.xsl` in `stepmod2mn` for copying the images for schemas.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 @ronaldtse, This seems to have gone off the rails somewhere. To clarify: ONLY if the clause 3 contains ONLY terms defined in ISO 10303 is the boilerplate 'see ISO 10303-2 etc., whatever that specific wording is'.
> 
> IF a specific resource or module clause 3 contains terms defined by OTHER THAN ISO 10303, those terms shall remain in that clause 3 and some boilerplate referring to ISO 10303-2 should also appear using whatever format etc. is required...

@TRThurman I would like to clarify the requirement. You wrote 'OTHER THAN ISO **10303**'. Does you mean '10303-**2**' or all parts '10303-*xxx*' (for instance '10303-1', '10303-44')?

**Comment by ronaldtse** [comment]
@Intelligent2013 it means all "ISO 10303-*" parts should be omitted, because ISO 10303-2 is a new publication that includes all terms. This means once we include ISO 10303-2 in the `source`, we do not need to import any other term from any ISO 10303-* document.

**Comment by Intelligent2013** [comment]
> 'Comments to reader',

![image](https://github.com/metanorma/stepmod2mn/assets/5559926/18d25829-2867-4972-9760-060e56e84354)

Unfortunately, we can't put it into the document attribute `:semantic-metadata-comments-to-reader:...`, because
- the text is multi-paragraph and Metanorma splits into multiple `<semantic-metadata><comments-to-reader>...</comments-to-reader></semantic-metadata>`
- the text contains the commas, and Metanorma splits the attribute value by comma into multiple `<semantic-metadata><comments-to-reader>...</comments-to-reader></semantic-metadata>` also.

I'll put 'Comments to reader' as comment into `document.adoc`, and may be we return to this task later if will be request.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 it means all "ISO 10303-*" parts should be omitted, because ISO 10303-2 is a new publication that includes all terms. This means once we include ISO 10303-2 in the `source`, we do not need to import any other term from any ISO 10303-* document.

@ronaldtse  thank you!

**Comment by Intelligent2013** [comment]
All done.
https://github.com/metanorma/stepmod2mn/releases/tag/v1.48
