### ISSUE TITLE
Issue with `[[term-...]]` anchors

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#151]
From: https://github.com/metanorma/iso-10303-srl/pull/33#discussion_r1552115291

`documents/iso-10303-1851/sections/03-terms.adoc`:

```
* [[term-datum_feature]]datum feature;
* [[term-datum_system]]datum system;
* [[term-datum_target]]datum target;
* [[term-situation_feature]]situation feature[[term-situation_feature]]situation feature.
```

Issue: there is a duplication of term: "situation feature situation feature"...

From @ronaldtse:
> Can we get rid of all the [[term-...]] anchors?

**Comment by Intelligent2013** [comment]
> Can we get rid of all the [[term-...]] anchors?

@ronaldtse would you like to remove `[[term-...]]` at all like this?
```
* datum feature;
* datum system;
* datum target;
* situation feature
```

**Comment by ronaldtse** [comment]
So and anchor is only useful if it was linked to. Has there been any links that link to “term-…”?

**Comment by Intelligent2013** [comment]
Done.
