### ISSUE TITLE
Remove all created anchors for terms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#153]
I did a search in iso-10303-stepmod-wg12, none of the terms are actually referenced. 

Let's not generate any ID for these terms anymore:
<img width="440" alt="Screenshot 2024-04-06 at 17 48 35" src="https://github.com/metanorma/iso-10303-srl/assets/11865/2a14adb9-db3b-4d5b-8b4a-614734df6671">

@Intelligent2013 can you please help remove all term anchors in stepmod2mn? Thanks.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-srl/pull/33#discussion_r1554558650_

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.40.
