### ISSUE TITLE
Rename all anchors like `AnnexF` or `AnnexG` to be meaningfully related to clause title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#156]
We have stuff like:

```
[[AnnexF]]
[appendix,obligation=informative]
== Change history
```

But
```
[[AnnexF]]
[appendix,obligation=informative]
== Application module implementation and usage guide
```

And these conflict in a document.

Instead of naming the anchors with sequential alphabets, let's use something like `[[change_history]]` and `[[usage_info]]` to prevent that from happening.

**Comment by Intelligent2013** [comment]
This issue was fixed in the latest `stepmod2mn`. But in any case I'll change the Annex's id.

**Comment by Intelligent2013** [comment]
Done.
