### ISSUE TITLE
SVG conversion changes with new style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#17]
Right now the SVGs built have this format:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" space="preserve" style="enable-background:new 0 0 595.28 841.89;" viewBox="0 0 368 315" y="0px" x="0px" id="Layer_1" version="1.1">
			<style type="text/css">.st0{fill:#FFFFFF;stroke:#000000;stroke-miterlimit:10;opacity:0}</style>
			<image xlink:href="data:image/gif;base64,..." height="315" width="368" style="overflow:visible;"></image>
			<a xlink:href="#basic_attribute_schema"><rect height="41" width="133" class="st0" y="186" x="210"></rect></a><a xlink:href="#action_schema"><rect height="41" width="86" class="st0" y="10" x="10"></rect></a><a xlink:href="#support_resource_schema"><rect height="41" width="148" class="st0" y="264" x="210"></rect></a>
		</svg>
```

We need to make these changes:
1. Remove `xlink` ns and also replace `xlink:href` with just `href`
2. For the shapes, add `onmouseout="this.style.opacity=0" onmouseover="this.style.opacity=1" style="opacity: 0; fill: rgb(33, 128, 255); fill-opacity: 0.3; stroke: rgb(0, 128, 255); stroke-width: 1px; stroke-linecap: butt; stroke-linejoin: miter; stroke-opacity: 1;"`
  * In the future we would want to use CSS to style these but it's not easy right now.
3. Remove `<style type="text/css">.st0{fill:#FFFFFF;stroke:#000000;stroke-miterlimit:10;opacity:0}</style>` because SVG classes are unscoped, they pollute the main CSS namespace with multiple definitions of `.st0`.

This is done in conjunction with metanorma/annotated-express#21.

**Comment by Intelligent2013** [comment]
@ronaldtse I've modified xslt for svg processing except `xlink:href` for `image` tag:

>     1. Remove `xlink` ns and also replace `xlink:href` with just `href`

`xlink` namespace is using for `image` tag also:
```xml
<image xlink:href="data:image/gif;base64,..." 
```
Do we need replace `xlink:href` with just `href` also here?

Here is example image with `xlink:href`: [action_schemaexpg1.zip](https://github.com/metanorma/stepmod2mn/files/6074955/action_schemaexpg1.zip)

Here is example image with `href`: [action_schemaexpg1.no_image_xlink.zip](https://github.com/metanorma/stepmod2mn/files/6074970/action_schemaexpg1.no_image_xlink.zip)

In Firefox both display ok.

**Comment by Intelligent2013** [comment]
`<image xlink:href="data:image/gif;base64` works ok. Closing.

**Comment by opoudjis** [comment]
... @Intelligent2013 I think you've misunderstood the ticket.

Because Safari is buggy, the requirement is that `image/@xlink:href` be globally replaced with `image/@href` in generated SVGs. See https://github.com/metanorma/annotated-express/issues/21

**Comment by ronaldtse** [comment]
@Intelligent2013 we need to implement this new mechanism because Safari doesn't work with the old method.

**Comment by Intelligent2013** [comment]
I've thought that xlink prefix should be removed from `a` hyperlink, but not from `image`. Now it removed fully.
