### ISSUE TITLE
Error P2 issue in iso-10303-1002

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#172]
documents/iso-10303-1002/sections/00-introduction.adoc

```diff
+
+_Error P2: Introduction does not start with required text: This document specifies ._
+
```

**Comment by Intelligent2013** [comment]
I can output this message on the console only, but omit in the adoc.

**Comment by Intelligent2013** [comment]
The error message commented in https://github.com/metanorma/iso-10303-srl/issues/197:
```
// _Error P2: Introduction does not start with required text: This document specifies ._
```

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.52.
