### ISSUE TITLE
Duplicated and unneeded anchors for Terms and definition clauses

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#175]
```
Anchor termsdefns has already been used at line 114
```

```adoc
[[defns]]
== Terms, definitions and abbreviated terms

[[termsdefns]]
[source=ref10303-2]
=== Terms and definitions

[[termsdefns]]
[heading=terms and definitions]
=== Terms and definitions

[[abbrv]]
=== Abbreviated terms

For the purposes of this document, the following abbreviated terms apply:

URL:: uniform resource locator
```

All the documents cannot be compiled now because of a duplicated anchor `termsdefns`.

Please don't add any anchor to these clauses because no one will ever refer to them:

```
[[defns]]
== Terms, definitions and abbreviated terms

[[termsdefns]]
[source=ref10303-2]
=== Terms and definitions

[[termsdefns]]
[heading=terms and definitions]
=== Terms and definitions

[[abbrv]]
=== Abbreviated terms
```

Thanks.

**Comment by ronaldtse** [comment]
And I don't understand -- how come `=== Terms and definitions` is duplicated using stepmod2mn-1.48.jar?

**Comment by Intelligent2013** [comment]
There was issue in applying changes from resource_docs for ISO 10303-2 terms. Fixed (not released yet).


> Please don't add any anchor to these clauses because no one will ever refer to them:

> `[[defns]]`

It's using in `00-introduction.adoc`:
```
... <<defns>> lists the words defined in this document and gives pointers to words defined elsewhere. ....
```

> `[[termsdefns]]`
> `[[abbrv]]`

currently there isn't any entrance of the reference, but `termsdefns` may be used in the element  `module_ref` (for'module' documents) or `refdoc_ref` (for 'reference_docs' documents).

Here is example for the anchor `scope`:
```xml
<li>items within the scope of application module <module_ref linkend="derived_shape_element:1_scope">Derived shape element</module_ref>, ISO/TS 10303-1130;</li>
```

It transforms to:
`01-scope.adoc`:
```adoc
...
* items within the scope of application module <<doc_iso10303-1130,anchor=scope>>, ISO/TS 10303-1130;
...
```
`99-bibliography.adoc`:
```adoc
...
* [[[doc_iso10303-1130,repo:(current-metanorma-collection/iso10303-1130)]]] (Derived shape element).
...
```

**Comment by Intelligent2013** [comment]
Duplicated section removed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.49.

'unneeded anchors for Terms and definition clauses' is an open question.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/iso-10303-srl/issues/202.
