### ISSUE TITLE
Convert Annex G (EXPRESS schema change history)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#18]
<img width="921" alt="Screenshot 2021-03-05 at 2 20 20 AM" src="https://user-images.githubusercontent.com/11865/110010520-56fe4d80-7d59-11eb-8f18-06c86e6444d2.png">
<img width="838" alt="Screenshot 2021-03-05 at 2 20 28 AM" src="https://user-images.githubusercontent.com/11865/110010534-5c5b9800-7d59-11eb-90c8-b56d3be5d8a8.png">
<img width="686" alt="Screenshot 2021-03-05 at 2 20 35 AM" src="https://user-images.githubusercontent.com/11865/110010548-6087b580-7d59-11eb-9a2f-437af15691b5.png">

This is based on the `changes.xml` file under `annotated-express/data/documents/resources/fundamentals_of_product_description_and_support`:

```xml
<changes>
   <change_edition version="2">
      <schema.changes schema_name="action_schema"><!-- 4 schema -->
         <description>
			The definitions of the following EXPRESS entity data types were modified:
			<ul>
               <li>action;</li>
               <li>action_directive;</li>
               <li>action_method;</li>
               <li>action_method_relationship;</li>
               <li>action_relationship;</li>
               <li>action_request_solution;</li>
               <li>action_request_status;</li>
               <li>action_resource;</li>
               <li>action_resource_relationship;</li>
               <li>action_resource_type;</li>
               <li>action_status;</li>
               <li>directed_action;</li>
               <li>executed_action;</li>
               <li>supported_item;</li>
               <li>versioned_action_request.</li>
            </ul>
         </description>
         <schema.modifications>
            <modified.object type="ENTITY" name="action"/>
            <modified.object type="ENTITY" name="action_directive"/>
            <modified.object type="ENTITY" name="action_method"/>
            <modified.object type="ENTITY" name="action_method_relationship"/>
            <modified.object type="ENTITY" name="action_relationship"/>
            <modified.object type="ENTITY" name="action_request_solution"/>
            <modified.object type="ENTITY" name="action_resource"/>
            <modified.object type="ENTITY" name="action_resource_relationship"/>
            <modified.object type="FUNCTION" name="acyclic_action_method_relationship"/>
            <modified.object type="FUNCTION" name="acyclic_action_relationship"/>
            <modified.object type="FUNCTION" name="acyclic_action_resource_relationship"/>
            <modified.object type="ENTITY" name="versioned_action_request"/>
         </schema.modifications>
      </schema.changes>
...
```

**Comment by Intelligent2013** [comment]
@ronaldtse sorry, I didn't understand the task. stepmod2mn converts AnnexG as part of whole document
iso-10303-stepmod/data/resource_docs/fundamentals_of_product_description_and_support/resource.xml
Here is resulted adoc: [document.txt](https://github.com/metanorma/stepmod2mn/files/6090486/document.txt)
(line #28136)

changes.xml looks as a cut out part from resource.xml
Would you like to convert specified changes.xml to adoc as standalone xml? I.e. stepmod2mn should support not only resource.xml as input format, but also some parts from it?

**Comment by ronaldtse** [comment]
This task is done in https://github.com/metanorma/stepmod-utils/issues/146

This means in stepmod2mn, we only need the AsciiDoc part that renders these new EXPRESS Change YAML files.

**Comment by Intelligent2013** [comment]
@ronaldtse how would you like to render the EXPRESS Change YAML files:
- as special mode (command line parameter) of stepmod2mn, or
- in the common XML to Adoc conversion (i.e. adoc + sections will be generated, and YAML files will be created in `resource` folder)
?

**Comment by ronaldtse** [comment]
I think in https://github.com/metanorma/stepmod-utils/issues/146 we already convert all Change XML files into Change YAML files.

We just need to render them inside Metanorma using a liquid template.

Technically we do not need stepmod2mn to do so, I think.

**Comment by Intelligent2013** [comment]
The requirements for liquid template (we need group the schema's changes by `edition`):
- iterate by `schemas.yaml/schemas`
- found all editions in the all `../../<schema>/<schema>.changes.yaml/change_edition/version`
- iterate by editions and process the changes from each `../../<schema>/<schema>.changes.yaml`

**Comment by Intelligent2013** [comment]
> We just need to render them inside Metanorma using a liquid template.

I'm trying to develop the liquid template. I've spent a half day and still it's magic for me.

- ### Problem 1
In the folder `/resources/action_schema` there are two `yaml`:
- `action_schema.changes.yaml` (created by `stepmod-utils`):
```yaml
---
schema: action_schema
change_edition:
- version: '2'
  description: |-
    The definitions of the following EXPRESS entity data types were modified:
...
```
- `test.yaml` - created manually for testing purposes:
```yaml
---
schemas:
  test:
    path: test.exp
```


Just for testing, in `data\resource_docs\fundamentals_of_product_description_and_support\97-change-history.adoc` I have:
```
[yaml2text,../../resources/action_schema/action_schema.changes.yaml,data]
----
this is content within the yaml2text block 1!
----

[yaml2text,../../resources/action_schema/test.yaml,data]
----
this is content within the yaml2text block 2!
----
```

In the Presentation XML (`bundle exec metanorma -t iso -x presentation document.adoc`) there is only second block (for `test.yaml`)
<p id="_">this is content within the yaml2text block 2!</p>

`action_schema.changes.yaml` - is valid (checked by https://www.yamllint.com/, https://yamlchecker.com/, https://jsonformatter.org/yaml-validator)

- ### Problem 2
`stepmod-utils` (`stepmod-extract-changes -p iso-10303-stepmod-master`) for the document 
`data\resource_docs\fundamentals_of_product_description_and_support\resource.xml` has created a few files `...changes.yaml`
```
data\resources\action_schema\action_schema.changes.yaml
data\resources\application_context_schema\application_context_schema.changes.yaml
data\resources\approval_schema\approval_schema.changes.yaml
data\resources\basic_attribute_schema\basic_attribute_schema.changes.yaml
data\resources\certification_schema\certification_schema.changes.yaml
data\resources\contract_schema\contract_schema.changes.yaml
data\resources\date_time_schema\date_time_schema.changes.yaml
data\resources\document_schema\document_schema.changes.yaml
data\resources\effectivity_schema\effectivity_schema.changes.yaml
data\resources\experience_schema\experience_schema.changes.yaml
data\resources\external_reference_schema\external_reference_schema.changes.yaml
data\resources\group_schema\group_schema.changes.yaml
data\resources\language_schema\language_schema.changes.yaml
data\resources\location_schema\location_schema.changes.yaml
data\resources\management_resources_schema\management_resources_schema.changes.yaml
data\resources\measure_schema\measure_schema.changes.yaml
data\resources\person_organization_schema\person_organization_schema.changes.yaml
data\resources\product_definition_schema\product_definition_schema.changes.yaml
data\resources\product_property_definition_schema\product_property_definition_schema.changes.yaml
data\resources\product_property_representation_schema\product_property_representation_schema.changes.yaml
data\resources\qualifications_schema\qualifications_schema.changes.yaml
data\resources\security_classification_schema\security_classification_schema.changes.yaml
data\resources\support_resource_schema\support_resource_schema.changes.yaml
```
Each yaml contains data for concrete schema (as expected).
We need to render changes grouped by edition (2, 3, ...), see the initial post, i.e.:
```
G.2 Changes made in edition 2
G.2.2 Changes made to schema action_schema
G.2.3 Changes made to schema application_context_schema
...
G.2.20 Changes made to schema support_resource_schema
G.3 Changes made in edition 3
G.3.2 Changes made to schema action_schema
G.3.3 Changes made to schema date_time_schema
...
G.4 Changes made in edition 4
G.4.2 Changes made to schema action_schema
...
```

@ronaldtse is there a way to pass a few files into `yaml2text` template?

**Comment by ronaldtse** [comment]
This work is being done by @manuelfuenmayor in:
* https://github.com/metanorma/iso-10303-templates/issues/11
