### ISSUE TITLE
Some citation to ISO 10303-2 is text in brackets when generating iso 10303 part 1064

### ISSUE THREAD

**Issue by kwkwan** [metanorma/stepmod2mn#185]
In section `3 Terms, definitions and abbreviated terms`, the citation `ref10303-2_iso-10303-1064` does not resolved properly.  In `03-terms.adoc`, the source is pointed to `ref10303-2`, which cannot be found in  `02-norm-refs.adoc`.
<img width="880" alt="Screenshot 2024-05-08 at 12 20 48 PM" src="https://github.com/metanorma/stepmod2mn/assets/29566367/3be0beef-a1a0-43a6-a0ae-c6ebf84581d7">

The Normative references of iso-10303-2 looks like:
```
* [[[bibitem_010303000002,ISO 10303-2]]], _Industrial automation systems and integration — Product data representation and exchange— Part 2: Vocabulary_
```

**Comment by ronaldtse** [comment]
@Intelligent2013 the work here is to use a consistent scheme in naming the bibliographic anchor for ISO 10303-2.

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.56.
