### ISSUE TITLE
Change all `document.adoc` to point to `../../schemas_all.yaml` instead of `schemas.yaml`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#187]
Needed in:
* https://github.com/metanorma/iso-10303-srl/pull/218

<img width="505" alt="Screenshot 2024-05-08 at 5 25 14 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/e2983002-08c0-4632-81f5-b9c9b89adad3">

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.56.
