### ISSUE TITLE
Change `00-introduction.adoc` `lutaml_express` section into an `include`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#189]
Needed in:
* https://github.com/metanorma/iso-10303-srl/pull/218

<img width="642" alt="Screenshot 2024-05-08 at 5 27 10 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/38a7b462-3f8a-4bff-9dcd-5a0458693f95">

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.56.
