### ISSUE TITLE
Schema descriptions (clause 4+) start with "General", then "Fundamental concepts and assumptions"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#19]
From metanorma/annotated-express#34

Schema descriptions (clause 4+) start with "General", then "Fundamental concepts and assumptions"

See metanorma/annotated-express@495facd for demonstration of this change.

**Comment by ronaldtse** [comment]
@Intelligent2013 there is a problem in the current implementation. The anchors are duplicated, e.g.:

```
[[schema6]]
== Approval schema

[[gen]]
== General

[[funcon]]
== Fundamental concepts and assumptions
```

Each anchor must be unique.

**Comment by Intelligent2013** [comment]
Issue fixed.
[document.adoc.txt](https://github.com/metanorma/stepmod2mn/files/6116148/document.adoc.txt)

**Comment by ronaldtse** [comment]
Thanks!
