### ISSUE TITLE
Errors should not kill the documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#191]
These errors should be made into comments after the document attributes. The generated document must always be valid for compilation.

<img width="693" alt="image" src="https://github.com/metanorma/stepmod2mn/assets/11865/b37bb679-73f5-43db-bb88-09f8edf4ecf0">

**Comment by Intelligent2013** [comment]
Empty lines don't supported between the document attributes:
```
= Industrial automation systems and integration: Product data representation and exchange: Application module: Project resources
:docnumber: 10303
:tc-docnumber: ISO/TC 184/SC 4/WG 12 N00000

// _Error in module.xml/module/@wg.number - Error WG-2: No WG number provided (0 is invalid)._

:partnumber: 1392
:copyright-year: 
:language: en
:publish-date: 
:edition: 1
:title-intro-en: Industrial automation systems and integration
:title-intro-fr: Systèmes d'automatisation industrielle et intégration
:title-main-en: Product data representation and exchange
:title-main-fr: Représentation et échange de données de produits
:title-part-en: Application module: Project resources
:title-part-fr: Module d'application: Project resources
```
The presentation XML doesn't contains the elements `title` at all.

The correct markup is:
```adoc
```
= Industrial automation systems and integration: Product data representation and exchange: Application module: Project resources
:docnumber: 10303
:tc-docnumber: ISO/TC 184/SC 4/WG 12 N00000
// _Error in module.xml/module/@wg.number - Error WG-2: No WG number provided (0 is invalid)._
:partnumber: 1392
:copyright-year: 
```

**Comment by ronaldtse** [comment]
@Intelligent2013 while you are at this, can you also strip the trailing whitespaces of the attributes? If there is no attribute value, please also strip the whitespace, e.g.

```adoc
:published-date:    // <=== Please strip whitespace
```

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.57.

Some documents, for instance `iso-10303-1137`, `iso-10303-1774`, `iso-10303-1818` don't generated by `stepmod2mn` anymore (they are missing in the repository index), therefore they didn't overwrite by new updated version, and still contain the non-commented `Error...` in the `document.adoc`. Therefore they should be removed manually from the folder `documents`.

**Comment by ronaldtse** [comment]
> Some documents, for instance iso-10303-1137, iso-10303-1774, iso-10303-1818 don't generated by stepmod2mn anymore

ALL documents should still be generated (and we MUST keep them). They should only be missing from `collection.yaml` but still kept in a separate YAML file to keep track that they are around.
