### ISSUE TITLE
Strip trailing whitespaces in titles and other document attributes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#193]
<img width="712" alt="Screenshot 2024-05-09 at 2 54 57 AM" src="https://github.com/metanorma/stepmod2mn/assets/11865/e49639a2-7611-4e28-a9fe-6e82cf863abf">
<img width="623" alt="Screenshot 2024-05-09 at 2 55 04 AM" src="https://github.com/metanorma/stepmod2mn/assets/11865/18e22f4e-05a8-4be7-a49a-6ea316ecd687">
<img width="767" alt="Screenshot 2024-05-09 at 2 55 15 AM" src="https://github.com/metanorma/stepmod2mn/assets/11865/433d0afe-7b11-4c6b-984f-93aa3305bc88">

**Comment by Intelligent2013** [comment]
Whitespace there is in the source XML:
```xml
<module name="presentation_hierarchy" 
	name.french="Hi&#233;rarchie de pr&#233;sentation "
```
I'll apply the `normalize-space` to the attributes values.

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.57.
