### ISSUE TITLE
Generate all documents regardless of `repository_index.xml`, `repository_index.xml` only affects what is in `collection.yaml`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#195]
> Some documents, for instance iso-10303-1137, iso-10303-1774, iso-10303-1818 don't generated by stepmod2mn anymore

ALL documents should still be generated (and we MUST keep them). They should only be missing from `collection.yaml` but still kept in a separate YAML file to keep track that they are around.

_Originally posted by @ronaldtse in https://github.com/metanorma/stepmod2mn/issues/191#issuecomment-2103614498_

**Comment by Intelligent2013** [comment]
@ronaldtse if we will generate ALL documents, then how to resolve the issue
https://github.com/metanorma/iso-10303-srl/issues/83?

There is two source `module.xml` with `part="433"`. The result folder is one - `iso-10303-433`.

From https://github.com/metanorma/iso-10303-stepmod-wg12/blob/TCSC410303-2256-wg12-stepdev_branch_for_srldev/data/modules/ap233_systems_engineering/module.xml:
```xml
<module
   name="ap233_systems_engineering"
   name.french="ing&#233;nierie des syst&#232;mes AP233"
   part="433"
```

From https://github.com/metanorma/iso-10303-stepmod-wg12/blob/TCSC410303-2256-wg12-stepdev_branch_for_srldev/data/modules/ap233_system_engineering_and_design/module.xml:
```xml
<module
   name="ap233_system_engineering_and_design"
   part="433"
...
```

**Comment by ronaldtse** [comment]
@Intelligent2013 good point, but for now please just rename one of them as iso-10303-443_2.

**Comment by Intelligent2013** [comment]
To do - generate 3 `collection` yaml:
- `collection.yaml` - for documents in `repository_index.xml` and not status `withdrawn`
- `collection.withdrawn.yml` -  for documents in `repository_index.xml` with status `withdrawn`
- `collection.missing.yml` - for document which missing in `repository_index.xml`

**Comment by Intelligent2013** [comment]
Also need 4th collection YAML file - `collection.wrong_part.yml` for the documents without `part` number or non-numeric `part`  number.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.58.
