### ISSUE TITLE
Genericise express_ref:[]

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#2]
Follow-on from https://github.com/metanorma/metanorma/issues/122:

Currently express_ref:[A] is used to generate cross-references between documents. We wish to genericise this solution. 

Each cross reference passed to express_ref is of form `schema ("." (prefix ".")* label)?`, where each of schema, prefix, label is a string that does not contain ".". So "action_schema.functions.type1" has schema = action_schema, prefix = functions, label = type1.

We wish `express_ref:[schema ("." (prefix ".")* label)]` to be replaced by the more generic syntax: `<<express:schema:prefix.label,label>>`. In other words, an Asciidoctor cross-reference, whose textual content (label) is the final string after the dot; and where the first string before a dot (the schema name) is separated from the remainder of the string.

So `express_ref:[action_schema.functions.type1]` will become `<<express:action-schema:functions.type1,type1>>`.

**Comment by Intelligent2013** [comment]
Done.

**Comment by Intelligent2013** [comment]
Here is resulted adocs with updated express refs: [Result.adoc.zip](https://github.com/metanorma/stepmod2mn/files/5824104/Result.adoc.zip)

**Comment by opoudjis** [comment]
As discussed previously, please change output of express_ref processing from `<<express:schema:prefix.label,label>>` to `<<express:schema:schema.prefix.label,label>>`

**Comment by Intelligent2013** [comment]
Done.
