### ISSUE TITLE
Update practices to latest iso-10303 repository

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#201]
## No need to generate express-g-diagrams.yaml

This functionality is now handled by:
* https://github.com/metanorma/iso-10303-templates/pull/30

<img width="736" alt="Screenshot 2024-10-04 at 12 12 23 PM" src="https://github.com/user-attachments/assets/22ede55b-87e2-4de8-8d42-bd8d878b2279">

## Strip paragraph whitespaces

<img width="838" alt="image" src="https://github.com/user-attachments/assets/a40d6134-2424-4f58-a8e6-447322406a3b">

<img width="851" alt="Screenshot 2024-10-04 at 12 27 55 PM" src="https://github.com/user-attachments/assets/9d2e8446-cebc-448e-ab8f-c7bf964fc87a">

## Change "change history annex" anchor to "annex_change_history"

<img width="830" alt="Screenshot 2024-10-04 at 12 27 28 PM" src="https://github.com/user-attachments/assets/7f853a6e-c6f1-4f76-b13b-a4432055dc4e">

**Comment by Intelligent2013** [comment]
> Strip paragraph whitespaces

The whitespaces occur due the text before/after the block elements like `p`, `ul`, `table`, etc.:

```xml
</p>
For a definition of the meaning of the other values, see ARM definition of Specification_expression.
```
```xml
</ul> There is no constraint to prevent both
```

```xml
</p>
     Among ISO 10303 series standards, ...
   <p>
```
```xml
</p>
Various inconsistencies can exist between:
<ul>
```
```xml
</p>
This document supports many possible uses of quality information for product shape data. These uses include the following.
<dl>
```

```xml
 <scope>
These constructs enable the representation of product data quality with a specific focus on 
three-dimensional product shape data and shape-related data. 
```

I'll add a patch into XSLT.

**Comment by Intelligent2013** [comment]
Another issue found - there isn't line breaks before definition list:
```adoc
 This document supports many possible uses of quality information for product shape data. These uses include the following. **Requirement for quality:**:: An ordering company requires the company receiving the order to create product data that satisfies prescribed quality requirements.
```

**Comment by ronaldtse** [comment]
Thank you! While you're at it, also strip the whitespace for clause titles:

```
===   xxx <-- has more than one space before title
```

**Comment by Intelligent2013** [comment]
Also, no line breaks before table id `[[table_E.1]]`:
```adoc
The symmetry primitive operators provide an alternative representation for geometry, built up from features. [[table_E.1]]
[cols="1,1"]
.table in tech_discussion
|===
|This is in Technical Discussion clause. |
|===
```

**Comment by Intelligent2013** [comment]
For xml:
```xml
<li>the following set theory relationships:
<ul>
<li>complement;</li>
<li>equivalence;</li>
<li>intersection;</li>
<li>power set;</li>
<li>proper subset;</li>
<li>subset;</li>
<li>union.</li>
</ul>
</li>
 </inscope>
```
the nested list markup is wrong:
```adoc
* the following set theory relationships:


* complement;

* equivalence;

* intersection;

...
```

I assume this occur due the missing `ul` for the parent list (missing `</ul>` before `</inscope>`. I'll fix it.

**Comment by Intelligent2013** [comment]
@ronaldtse all fixed in https://github.com/metanorma/stepmod2mn/releases/tag/v1.61.
