### ISSUE TITLE
Handle conversion of schema_diagexpg1.svg to `svgmap`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#21]
In the metanorma/iso-10303-stepmod repo, each resource_docs document contains one or more `schema_diagexpg{number}.svg` files. These diagrams point the different schemas inside the document.

<img width="375" alt="Screenshot 2021-03-25 at 10 53 07 PM" src="https://user-images.githubusercontent.com/11865/112493155-de6d3880-8dbc-11eb-8ff1-16164b9769b7.png">

For example, from `schema_diagexpg1.xml` we know that this `svgmap` is to be built:

```adoc
.The schemas of this part of ISO 10303
[.svgmap]
====
image::../schema_diagexpg1.gif[]

* <<express:group_schema>>; 1
* <<express:qualifications_schema>>; 2
* <<express:location_schema>>; 3
* <<express:management_resources_schema>>; 4
* <<express:measure_schema>>; 5
* <<express:person_organization_schema>>; 6
* <<express:security_classification_schema>>; 7
* <<express:experience_schema>>; 8
* <<express:application_context_schema>>; 9
* <<express:product_definition_schema>>; 10
* <<express:product_property_definition_schema>>; 11
* <<express:product_property_representation_schema>>; 12
* <<express:action_schema>>; 13
* <<express:approval_schema>>; 14
* <<express:certification_schema>>; 15
* <<express:date_time_schema>>; 16
* <<express:contract_schema>>; 17
* <<express:document_schema>>; 18
* <<express:effectivity_schema>>; 19
* <<express:external_reference_schema>>; 10
* <<express:basic_attribute_schema>>; 11
* <<express:support_resource_schema>>; 12
====
```

And this code should be placed in 01-introduction.doc (the end of clause 1).

**Comment by Intelligent2013** [comment]
Almost all (except header and `../` in path) was done earlier.
Updated. [document.adoc.txt](https://github.com/metanorma/stepmod2mn/files/6206382/document.adoc.txt)

> And this code should be placed in 01-introduction.doc (the end of clause 1).

stepmod2mn generates one .adoc file. It means that it should generate multiple files structure like this:
https://github.com/metanorma/annotated-express/tree/master/data/documents/resources/fundamentals_of_product_description_and_support/sections ?

**Comment by ronaldtse** [comment]
@Intelligent2013 yes please, because it would be very difficult to work with a file that long.

Could you also have a look at the structure of the latest document (the link you have) to ensure that the converted output compiles with this structure and content? Because this is the exemplary document that will be applied across all resource_docs.

Thanks!

**Comment by Intelligent2013** [comment]
stepmod2mn updated for generating each section in a separate file (https://github.com/metanorma/stepmod2mn/releases/tag/v1.7)
