### ISSUE TITLE
Fix sections structure

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#22]
Source: https://github.com/metanorma/stepmod2mn/issues/21#issuecomment-807846079
### 1. Section Scope

Current structure in resulted PDF:

![изображение](https://user-images.githubusercontent.com/5559926/112949919-613a1e80-9142-11eb-8d9b-7a9f396027ec.png)

Expected result:

![изображение](https://user-images.githubusercontent.com/5559926/112950000-7a42cf80-9142-11eb-9e81-77afb059b896.png)

### 2. Section Terms, definitions and abbreviated terms

Current structure in resulted PDF:

![изображение](https://user-images.githubusercontent.com/5559926/112950463-fdfcbc00-9142-11eb-87b5-d78d0f98f11c.png)

Expected result:
![изображение](https://user-images.githubusercontent.com/5559926/112950510-0bb24180-9143-11eb-8df2-7c48b72b8c72.png)

**Comment by Intelligent2013** [comment]
### 3. Incorrect sections nesting
![изображение](https://user-images.githubusercontent.com/5559926/113007361-d4fa1c80-917e-11eb-9c1a-78ef10c880d5.png)

Expected result:
![изображение](https://user-images.githubusercontent.com/5559926/113007761-299d9780-917f-11eb-8eb7-47617d8e6a36.png)

**Comment by Intelligent2013** [comment]
### 4. Figure 1 doesn't exist in resulted PDF:

![изображение](https://user-images.githubusercontent.com/5559926/113034717-1698c080-919b-11eb-815b-93856ca4b4f9.png)


### 5. Source code doesn't displaying correctly:

![изображение](https://user-images.githubusercontent.com/5559926/113034858-3f20ba80-919b-11eb-86ca-3cda29256527.png)

Expected result:
![изображение](https://user-images.githubusercontent.com/5559926/113034940-5a8bc580-919b-11eb-9d9c-c66798920c85.png)

**Comment by Intelligent2013** [comment]
### 6. NOTE 1 doesn't look correct:

![image](https://user-images.githubusercontent.com/5559926/114226516-51a9a980-997c-11eb-8c33-c52b8384e612.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 this NOTE 1 needs to be this snippet from the annotated-express template:

https://github.com/metanorma/annotated-express/blob/master/data/documents/resources/fundamentals_of_product_description_and_support/sections/04-schemas.adoc

```
[NOTE]
====
The schemas referenced above are specified in the following parts:

{% assign reference_froms = schema.interfaces | where: "kind", :REFERENCE %}
{% for from in reference_froms %}
{% assign from_schema = context.schemas | where: "id", from.schema.id | first %}
{% assign version = from_schema.version %}
{% assign version_number = version.items[2].value %}
{% assign version_part = version.items[3].value %}

{{ from_schema.id }}:: ISO {{ version_number }}-{{ version_part }}
{% endfor %}
====
```

**Comment by ronaldtse** [comment]
I think stepmod2mn only needs to generate certain sections, because many will be generated by the templates.

**Comment by Intelligent2013** [comment]
Done as snippet.
