### ISSUE TITLE
Change syntax for NOTE and EXAMPLE as per new syntax

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#24]
The Annotated EXPRESS syntax has been updated to treat NOTEs and EXAMPLEs as separate tagged remarks:
* https://github.com/metanorma/annotated-express/issues/103

The relevant code in stepmod2mn is this:
https://github.com/metanorma/stepmod2mn/blob/7eea23cfdb315e60177c30cef92749972a78e348/src/main/resources/stepmod2mn.adoc.xsl#L544-L607

i.e.

### EXAMPLE

Instead of:
```
[example]
====
Change, distilling, design, a process to drill a hole, and a task such as training someone, are examples of activities.
====
```

We generate this:
```
(*"Activity_arm.Activity.__example"
Change, distilling, design, a process to drill a hole, and a task such as training someone, are examples of activities.
*)
```

### NOTE

Instead of:
```
[NOTE]
--
Status information identifying the level of completion of each activity may be provided within an instance of <<express:Activity_arm.Activity_status,Activity_status>>.
--
```

We have this:
```
(*"Activity_arm.Activity.__note"
Status information identifying the level of completion of each activity may be provided within an instance of <<express:Activity_arm.Activity_status,Activity_status>>.
*)
```

The EXAMPLEs and NOTEs do not need to be numbered.

**Comment by Intelligent2013** [comment]
Done in stepmod2mn v.1.8: https://github.com/metanorma/stepmod2mn/releases/tag/v1.8

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
