### ISSUE TITLE
Limited escaping of formatting commands in generated Asciidoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#3]
`_` in Asciidoc strings must not be escaped in general. Refer to https://docs.asciidoctor.org/asciidoc/latest/text/

Words in Asciidoc are delimited by blank space or punctuation (`,;".?!`). In a word, formatting characters, *_\`#~^, are only to be escaped  if they can be processed as formatting characters:

* For any formatting character `<F>`,
  * `\A(<F>)(.+)\1\Z` =>   `\\\1\2\1`: escape an initial formatting character only if they occur at the start and end of the word. So `_abc_` => `\_abc`, but not `a_bc_` and not `_abc`.
  *  `\A(.*)(<F>)\2(.+)\2\2(.*)\Z` =>   `\1\\\2\2\3\2\2\4`: escape the first of four formatting character, only if there is are two instances of pairs of the formatting character within the word (at any place). So `a__b__c_d` => `a\__b__c_d`, but not `a_b__c` or `__abc`

As I said, it is very rare that you need to escape a formatting character in Asciidoctor at all, but the conditions for where you do are more complex.

**Comment by Intelligent2013** [comment]
To do:
1. make two step xslt - move `b`, `i`, `sub`, etc. processing at 2nd step.
2. escape text for text and values from attributes at 1st step. (java regex extension or by java code)
3. instead of `<xsl:value-of select="@..` - do <xsl:apply-templates select="@..."` with escaping.

**Comment by Intelligent2013** [comment]
And it should be a common approach for another .xml to .adoc converters too.

**Comment by Intelligent2013** [comment]
Done.
