### ISSUE TITLE
Fixes to collection scripts

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#45]
* [x] collection.sh

````
./html_attachments.sh
````

should be

````
sh ./html_attachments.sh
````

* [x] The images expected in sections/94-expressg-diagrams.adoc and sections/00-introduction.adoc (in resources/*/*.* and resource_docs/*.*) are SVG images. The raw images in iso-10303-stepmod-wg12 are GIF. This means that an additional step needs to be run by someone, to generate SVG images out of the provided GIF files. This has been done in annotated-express, but I don't know who has done it.

Without the SVG conversion, the documents cannot be generated. That means that stepmod2mn needs to do the SVG conversion.

* [x] The directory paths generated to /resources from /sections are ../../../../resources throughout. They need to be ../../../throughout. This applies to:

* sections/94-expressg-diagrams.adoc , the SVG links
* sections/00-introduction.adoc , schema_diagexpg1.gif

**Comment by Intelligent2013** [comment]
> Without the SVG conversion, the documents cannot be generated. That means that stepmod2mn needs to do the SVG conversion.

stepmod2mn supports the SVG generation in the separate call:
```
java -jar target/stepmod2mn-1.12.jar data/ --svg
```
https://github.com/metanorma/annotated-express/issues/124#issuecomment-1712826234

**Comment by Intelligent2013** [comment]
> The directory paths generated to /resources from /sections are ../../../../resources throughout. They need to be ../../../throughout. 

@opoudjis I look at https://github.com/metanorma/stepmod2mn/blob/main/src/main/resources/stepmod.base_xsl/res_doc/resource.xsl#L1757C11-L1757C11. The path was changed specially to 4 levels up `image::../../../../resources/action_schema/action_schemaexpg1.svg[]` for https://github.com/metanorma/stepmod2mn/issues/14#issuecomment-785857308 2.5 years ago.

I can change to 3 levels up `image::../../../resources/action_schema/action_schemaexpg1.svg[]`, no problem at all. But _may be_ 4 levels is using when we run metanorma in one-document generation mode, but 3 levels in the collection processing mode?
Just want to confirm.

**Comment by opoudjis** [comment]
Asciidoctor really does not cope well with assets being in different locations from the source document. But, the compilation of one-document generation is a necessary precursor to any collection processing: the collection processing happens on the XML generated in one-document generation mode, and when that happens, we (by default, for good reason) embed the images inside the XML.

The ticket... look, to be honest, I don't understand what is going on, because the relative paths confuse me; all I know is, if we're compiling the files in the context, the 4 levels break one-doc generation mode (that's what I'm doing right now, the initial compilation of document.adoc); and that ticket was done for annotated-express, not this context.

The two options you presented btw aren't related to this issue; whichever of the two options is used, we're not getting to the right source image.

**Comment by Intelligent2013** [comment]
All done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.13.
