### ISSUE TITLE
Images issues

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#49]
The generated document document.adoc in fundamentals_of_product_description_and_support contains

`:imagesdir: images`

But the images are *not* in an images directory, so that line needs to go.

The SVGs... have gone again. I wonder if I was misled by the images subdirectory! In order to compile, the image links in sections/94-expressg-diagrams.adoc need to be:

`image::../../resources/action_schema/action_schemaexpg2.svg[]`

Right now, they are ../../../

The same needs to be done with the references to /resources in collection.yml

**Comment by opoudjis** [comment]
https://github.com/metanorma/annotated-express/issues/124

**Comment by Intelligent2013** [comment]
Done.
https://github.com/metanorma/stepmod2mn/releases/tag/v1.14.
