### ISSUE TITLE
Annexes in 10303-41 have wrong anchors

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#55]
How you address this, I don't know,  but:

* The generated annexes of 10303-41 have generic anchors: AnnexA, AnnexB, AnnexC, AnnexE. Only AnnexD has the anchor expg
* However, the generated clauses expect the annexes to have semantic anchors. So Clause 4 starts with:

````
<p id="_76ccc8fd-a5bf-f93a-3e2e-f51c6085839c">Short names of entities defined in this schema are described in
<xref target="short_entity_names"/>. 
Unambiguous identification of this schema is defined in
<xref target="info_object_reg"/>.</p>
````

Those are intended as links to Annex A and Annex B, respectively. Presumably somewhere in the source for those annexes, those identifiers appear and can be extracted.

https://github.com/metanorma/annotated-express/issues/124

**Comment by Intelligent2013** [comment]
Fixed.
