### ISSUE TITLE
Create symbolic link to 04-schemas.adoc 

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#58]
Source issue: https://github.com/metanorma/stepmod2mn/issues/52#issuecomment-1718814874

As titled.

**Comment by Intelligent2013** [comment]
I'm trying to create the symbolic link by the Java method `Files.createSymbolicLink(link, target)`
```
Cannot create the symbolic link "D:\Work\Metanorma\repositories\iso-10303-stepmod.copy02\data\resource_docs\fundamentals_of_product_description_and_support/sections/04-schemas.adoc" for the file D:\Work\Metanorma\repositories\iso-10303-stepmod.copy02\data\resource_docs\fundamentals_of_product_description_and_support\/../../../04-schemas.adoc.
A required privilege is not held by the client.
```

The reason: admin rights only allows by default to create the symbolic links on Windows. Or need to edit Local Policies.
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

I propose to copy the template from `../../../04-schemas.adoc` to the current folder `sections/...`.

**Comment by Intelligent2013** [comment]
`stepmod2mn` copies `../../../04-schemas.adoc` into the current folder `sections/04-schemas.adoc`. Done.

**Comment by ronaldtse** [comment]
But this is copying - after the documents are generated, how do I keep the 04-schemas file in sync? On macOS and Linux I want to have symbolic links. 

On Windows, apparently you can still make links without being admin:

https://stackoverflow.com/questions/58038683/allow-mklink-for-a-non-admin-user

> Non admin users can make directory links using 'mklink /J'

**Comment by Intelligent2013** [comment]
> On Windows, apparently you can still make links without being admin:
> 
> https://stackoverflow.com/questions/58038683/allow-mklink-for-a-non-admin-user
> 
> > Non admin users can make directory links using 'mklink /J'

@ronaldtse thank you for the advice! Yes, it's working without admin rights, but for the _folders only_. Therefore we need to put `04-schemas` into some folder, for instance `sections_common`, i.e. the repo structure is:
```
.../iso-10303-stepmod/
   data/
     resource_docs/fundamentals_of_product_description_and_support/
   ...
   sections_common/04-schemas.adoc

```

and then make `mklink /J ...`. After that we will have:
```
.../iso-10303-stepmod/
   data/
     resource_docs/fundamentals_of_product_description_and_support/
       sections\
       sections_common\04-schemas.adoc (-> ../../../sections_common/04-schemas.adoc)
       document.adoc
   ...
   sections_common/04-schemas.adoc

```

In `document.adoc`:
```
...
include::sections/03-terms.adoc[]

include::sections_common/04-schemas.adoc[]
...
```

Further tasks:
- [ ] investigate how to create junction via Java API
- [ ] update Java code to create symlink for Linux and MacOS, and junction for Win platforms.

**Comment by ronaldtse** [comment]
@Intelligent2013 very happy with a shared common folder, can you please help implement?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 very happy with a shared common folder, can you please help implement?

@ronaldtse done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.16

`sections_common/04-schemas.adoc` added in `iso-10303-stepmod` in the commit
https://github.com/metanorma/iso-10303-stepmod/commit/797922aabfb7d2c816067ad2ef97cfb8935b693b (branch `update`).

**Comment by opoudjis** [comment]
I am working on branch SMRLv9. I need sections_common to be on that branch. Until that is resolve, this ticket is not. 

This workflow is profoundly fragile, and the request of adding static content to a dynamically generated repository has been very unhelpful.

**Comment by opoudjis** [comment]
It's not static, it's an artefact of conversion. In  my opinion, it's either stepmod2mn or stepmod-utils. @ronaldtse ?

**Comment by opoudjis** [comment]
@Intelligent2013 !

YOU MUST FIX THIS!!!

I cannot constantly have things crashing on this god-forsaken repository because you are not generating the files I need for compilation.

**Comment by Intelligent2013** [comment]
@ronaldtse 

> We need to determine the source of sections_common. It could be:
> - internal resource in `stepmod2mn.jar`

I propose to distribute the template `sections_common\04-schemas.adoc` as internal resource of `stepmod2mn`. I.e. in case of changes of `04-schemas.adoc` we have to change in in the `stepmod2mn` repository. Do you agree?

**Comment by opoudjis** [comment]
Yes.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.23.
