### ISSUE TITLE
Imagemap areas in SVGs are misaligned

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#63]
The attached SVG is generated by stepmod2mn for ISO 10303-41. As you can see by mousing over it in a browser, the image mapped rectangles in the SVG are not aligned with the rectangles in the drawing: the coordinates are off. They do not seem to be off in a consistent way, I fear.

[schema_diagexpg1.svg.zip](https://github.com/metanorma/stepmod2mn/files/12620141/schema_diagexpg1.svg.zip)

**Comment by opoudjis** [comment]
https://github.com/metanorma/annotated-express/issues/124

**Comment by Intelligent2013** [comment]
For testing, I've set `opacity: 1` for all `polygon`s . As you can see, there is a difference between rectangles order/structure on the GIF image and SVG graphics:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/8338c123-f66f-40af-991d-c62201027454)

And two columns structure in the `schema_diagexpg1.xml`:

![image](https://github.com/metanorma/stepmod2mn/assets/5559926/91ea0cfe-b20f-48b3-8acf-fad30ff29d76)

Another SVG (`resource_docs/finite_element_analysis_definition_relationships/schema_diagexpg1.svg`) looks ok:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/b510a022-53c3-4f49-ad82-10acd4efa67c)

So, it's source data issue.

**Comment by opoudjis** [comment]
@ronaldtse @TRThurman ... which means we need an escalation of this, and I don't know who escalates it. This specific diagram was working three years ago...

**Comment by ronaldtse** [comment]
@opoudjis a number of image map diagrams have this issue and it's a source problem. We don't need to fix them now.

**Comment by TRThurman** [comment]
Confirmed.
Figure 1 in part 41, 42, 43 are problematic. Part 44 appears ok. So when we get around to part 44, we should verify the conversion to annotated EXPRESS is valid.
