### ISSUE TITLE
Corrupt document header in resource_docs/logical_model_of_expressions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#71]
This is clearly a source data issue (note @TRThurman ), but I'm reporting it here because it impinges on Asciidoc generation:

````
= Industrial automation systems and integration: Product data representation and exchange: 
_Error : unknown type, part number:13584-20_

: Logical model of expressions
:docnumber: 10303
:tc-docnumber: 10524
:partnumber: 13584-20
:copyright-year: 2013
:language: en
:publish-date: 
:edition: 2
:title-intro-en: Industrial automation systems and integration
:title-intro-fr: Systèmes d'automatisation industrielle et intégration
:title-main-en: Product data representation and exchange
:title-main-fr: Représentation et échange de données de produits
:title-part-en: 
_Error : unknown type, part number:13584-20_

: Logical model of expressions
:title-part-fr: 
_Error : unknown type: _Error : unknown type, part number:13584-20__

:
:doctype: international-standard
````

**Comment by TRThurman** [comment]
ISO 13584-20 is not to be included as a document in the collection.
notice that the resource.xml does not have a docnumber attribute, which is the problem. The designers of the XSLT assumed all parts were ISO 10303 parts.

This is a more appropriate source header:

: Logical model of expressions
:docnumber: 13584
:tc-docnumber: 10524
:partnumber: 20
...
I can't fix the resource.xml without ugly side effects (I could propose a 'docnumber' but don't have the bandwidth to fix the XSLT scripts that generate the current SMRL.
Can we get by with a local patch to the :docnumber and :partnumber variables?

**Comment by ronaldtse** [comment]
@Intelligent2013 can you please have a look at this? We just need to exclude the ISO 13584-20 document. Thanks.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can you please have a look at this? We just need to exclude the ISO 13584-20 document. Thanks.

@ronaldtse will be done in https://github.com/metanorma/stepmod2mn/issues/75.

**Comment by opoudjis** [comment]
Confirmed
