### ISSUE TITLE
Change the movement of error files in html_attachments.sh

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#79]
As of the last releaase of Metanorma, error files are no longer generated as *.err, but as *.err.html

html_attachments.sh needs to be updated to deal with the new filename extension for error logs:

````
rename drawing_definition_schema.err to sections/schemadocs/drawing_definition_schema.err: No such file or directory
````

**Comment by Intelligent2013** [comment]
Done.
