### ISSUE TITLE
Generate SVG files

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#8]
The ISO-10303 Stepmod repository, when it is converted to asciidoc-oriented express files via this code, includes Express XML image maps, which appear to be ported from the original. I don't understand how, and I don't really want to. :-)

So in https://github.com/metanorma/iso-10303-stepmod/tree/master/data/resources/basic_attribute_schema, 

we have https://github.com/metanorma/iso-10303-stepmod/blob/master/data/resources/basic_attribute_schema/basic_attribute_schemaexpg1.gif and https://github.com/metanorma/iso-10303-stepmod/blob/master/data/resources/basic_attribute_schema/basic_attribute_schemaexpg1.xml

The latter looks like this:

````
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/res_doc/imgfile.xsl"?>
<!DOCTYPE imgfile.content SYSTEM "../../../dtd/text.ent">
<imgfile.content module="fundamentals_of_product_description_and_support" file="basic_attribute_schemaexpg1.xml">
<img src="basic_attribute_schemaexpg1.gif">
<img.area shape="rect" coords="157,98,305,139" href="../../resources/support_resource_schema/support_resource_schema.xml" />
<img.area shape="rect" coords="10,10,143,51" href="../../resources/basic_attribute_schema/basic_attribute_schema.xml" />
</img>
</imgfile.content>
````

We will be using SVG as our image map format, as detailed in https://github.com/metanorma/annotated-express/issues/15

This task is to create a stylesheet to convert the Express imagemap files and gifs into SVG files. We want the gif files to be included in the SVG file as a data uri. Example: 

[action_schemaexpg1.svg.zip](https://github.com/metanorma/stepmod-utils/files/5893858/action_schemaexpg1.svg.zip)

As described in https://github.com/metanorma/metanorma/issues/160, the target output should look like this:

````
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 WIDTH HEIGHT" style="enable-background:new 0 0 595.28 841.89;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;stroke-miterlimit:10;}
</style>
<image style="overflow:visible;" width="WIDTH" height="HEIGHT" xlink:href="data:image/gif;base64,..." transform="matrix(1 0 0 1 114 263.8898)">
</image>
<a xlink:href="../../resources/support_resource_schema/support_resource_schema.xml" >
	<rect x="123.28" y="273.93" class="st0" width="88.05" height="41.84"/>
</a>
<a xlink:href="../../resources/basic_attribute_schema/basic_attribute_schema.xml" >
	<rect x="324.69" y="450.52" class="st0" width="132.62" height="40.75"/>
</a>
</svg>
````

where

* WIDTH is the GIF width
* HEIGHT is the GIF height
* xlink:href="data:image/gif;base64,..." is a Data URI encoding of the GIF
* I have no idea what the `image/@transform` attribute does
* svg supports rect, circle, ellipse, and polygon arguments
* The Express XML image map coordinates for shapes appear to be the same as HTML image maps
* Express/HTML `<img.area shape="rect" coords="x1,y1,y2,y3">` corresponds to ` <rect x="x1" y="y1" fill="#fff" opacity="0" width="x2-x1" height="y2-y1" />`
* I don't know what the class attribute is for

If there are other shapes in the Express Image maps, they will have to be converted correctly as well; see https://github.com/metanorma/metanorma/issues/160 (and online documentation of SVG). Ditto the SVG attributes I don't understand.

The content of the HREFs can be any URI, but to keep things straightforward for further processing, we will use the file paths to XML files that are in the original Express Imagemaps, like `"../../resources/support_resource_schema/support_resource_schema.xml"`.

I don't know where the source XML comes from, and whether you just update them in place. That is a discussion between you, @ronaldtse, and @zakjan.

**Comment by ronaldtse** [comment]
This is all done. Thanks @Intelligent2013 !
