### ISSUE TITLE
Generate adoc in the source folder

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#88]
Source ticket: https://github.com/metanorma/annotated-express/issues/124#issuecomment-1777504209

Currently, `stepmod2mn` generates adoc in the folder `--output <...>`.
To do:
- generate adoc in the source folder (in the place of `resource.xml`)
- the `--output` value should be used only in the `collection.sh` for copying source folder into `documents/resources/...`
- modify `collection.sh`:
```sh
for name in $INPUT_REPOS
do
  echo $name
  cd data/resource_docs/resources/$name
  sh ./html_attachments.sh
  bundle exec metanorma -x xml document.adoc
  cd  ../../..
  cp -R  data/resource_docs/resources/$name documents/resources/$name
done
```

i.e. `  cd data/resource_docs/resources/$name` is constant line (no need to change it)
`  cp -R  data/resource_docs/resources/$name documents/resources/$name` for copy metanorma xml into the output `documents/resources/...` folder

**Comment by ronaldtse** [comment]
I don’t want to generate anything in the source folder. Everything needs to be in the destination directory.

**Comment by Intelligent2013** [comment]
> I don’t want to generate anything in the source folder. Everything needs to be in the destination directory.

@ronaldtse then I absolutely don't understand what should I do...
From https://github.com/metanorma/annotated-express/issues/124#issuecomment-1777504209

> completely abandon the attempt to copy files and break the relative links already in place; compile the documents in the data/resource_docs/fundamentals_of_product_description_and_support locations where they are, and copy the entire directories AFTER compilation to the new documents/resources/fundamentals_of_product_description_and_support folder

ping @opoudjis

**Comment by Intelligent2013** [comment]
The updates in this issue are wrong, because

> Nothing should be done in place.
> Nothing should affect the source input directory

**Comment by Intelligent2013** [comment]
Closing due wrong initial requirement, no need to change `stepmod2mn`, because

> I don’t want to generate anything in the source folder. Everything needs to be in the destination directory.
