### ISSUE TITLE
Generate bibliographic references to other parts of the collection

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#94]
Follow-on from https://github.com/metanorma/annotated-express/issues/138

Part 41 Clause 23.1 Note 1 has blank references to other 10303 documents. If they are marked up in Express as bibliographic references, they need to be marked up in the generated Asciidoctor as bibliographic references as well. If they are pure text, they need to be rendered as text.

Source document:

![image](https://github.com/metanorma/stepmod2mn/assets/1911039/31650aa3-710c-4371-90ae-b5e4bfefbe7e)

Rendering:

![image](https://github.com/metanorma/stepmod2mn/assets/1911039/1425bf07-0cb8-457a-af91-c19f18e439cc)

The references from ISO 10303-41 to itself are populated; the references to ISO-10303-x are being left completely blank. (Giving XML output, because the Asciidoctor generated by Lutaml is inaccessible. @ronaldtse Get that fixed.)

````
<note id="_b9d78e81-52e4-5632-5f57-a326fa12b8f8"><index><primary>basic_attribute_schema</primary><secondary>Schema interface</secondary></index><index><primary>process_property_schema</primary><secondary>Schema interface</secondary></index><index><primary>product_definition_schema</primary><secondary>Schema interface</secondary></index><index><primary>product_property_representation_schema</primary><secondary>Schema interface</secondary></index><index><primary>product_structure_schema</primary><secondary>Schema interface</secondary></index><index><primary>shape_dimension_schema</primary><secondary>Schema interface</secondary></index><index><primary>shape_tolerance_schema</primary><secondary>Schema interface</secondary></index><index><primary>support_resource_schema</primary><secondary>Schema interface</secondary></index><p id="_2662ed58-ea7f-c734-ed9d-bcc16629fc83">The schemas referenced above are specified in the following parts:</p>

<dl id="_33f0b674-41ab-fcea-a169-d48a8f207ae3"><dt>basic_attribute_schema</dt>
<dd><p id="_a429e251-39d5-74c0-c7ff-56d782dd5113">ISO 10303-41</p>
</dd>
</dl>

<p id="_bfc2142e-4cbb-00ab-46de-3e0184a5cdcf">:: ISO -</p>

<dl id="_3f671c2d-800e-1788-13c0-ceef8209cb71"><dt>product_definition_schema</dt>
<dd><p id="_e0432c8b-d8c7-7eb2-2153-03b6bbcfeaaf">ISO 10303-41</p>
</dd>
<dt>product_property_representation_schema</dt>
<dd><p id="_c2fcd87f-38a1-4bad-5b82-f079de2f6ff8">ISO 10303-41</p>
</dd>
</dl>

<p id="_e31d9807-052a-cdba-585b-3e70d12e7725">:: ISO -</p>

<p id="_15a31c0f-7e5d-c847-1808-27663da2d781">:: ISO -</p>

<p id="_0f739da5-190f-9e7e-9a3f-5f3f7f425040">:: ISO -</p>

<dl id="_78305be8-71f2-9514-5c6d-7ea2f042f5fb"><dt>support_resource_schema</dt>
<dd><p id="_10350a12-f485-e168-d981-6a4f3c03151e">ISO 10303-41</p>
</dd>
</dl>
</note>
````

**Comment by ronaldtse** [comment]
> the references to ISO-10303-x are being left completely blank. 

For the avoidance of doubt, where is this NOTE being generated from?

We have this code in `annotated-express` in a file `04-schemas.adoc`, but it is deprecated.

```liquid
[NOTE]
====
The schemas referenced above are specified in the following parts:

{% assign reference_froms = schema.interfaces | where: "kind", :REFERENCE %}
{% for from in reference_froms %}
{% assign from_schema = context.schemas | where: "id", from.schema.id | first %}
{% assign version = from_schema.version %}
{% assign version_number = version.items[2].value %}
{% assign version_part = version.items[3].value %}

{{ from_schema.id }}:: ISO {{ version_number }}-{{ version_part }}
{% endfor %}
====
```

**Comment by opoudjis** [comment]
That is indeed where it is generated.

**Comment by ronaldtse** [comment]
Maybe don't close this yet, should we generate some warning in place just in case?

**Comment by opoudjis** [comment]
This is Lutaml stuff. I deal with the Asciidoc it generates, and that alone. I therefore have no ability to generate a warning, and no understanding of where it would need to be done. If you want a warning, make a new ticket somewhere else.
