### ISSUE TITLE
Move output folder for collections.sh

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#98]
I have been generating multiple collections from the same source data in ISO 10303

````
STEPMOD2MN=/Users/nickn/Documents/Arbeit/upwork/ribose/stepmod2mn/target/stepmod2mn-1.22.jar

declare -a arr=(
"CR_TEST_00041-00045"   
"CR_TEST_00046-00051"
"CR_TEST_00052-00057"           
"CR_TEST_00058-00088"   
"CR_TEST_00101-00108"
"CR_TEST_00109-00113"           
"CR_TEST_00501-00505"
"CR_TEST_00506-00510"
"CR_TEST_00511-00515"
"CR_TEST_00517-00523"
)


for f in "${arr[@]}"
do
echo $f
java -Xss5m -jar $STEPMOD2MN iso-10303-stepmod/publication/part1000/$f/publication_index.xml --output iso-10303-stepmod/$f
cd iso-10303-stepmod
sh collection.sh
mv iso10303-output ${f}_output
cd ..
done
````

And because Expressir is constantly crashing on my machine for reasons unknown, I can't run the foregoing as a script, since I need to run STEPMOD2MN 2-3 times for each publication index separately.

Notice though that the output directory of the collection is always hardcoded in collections.sh to iso-10303-stepmod, so I have to move the output directory after each run into a new location:

````
cd iso-10303-stepmod
sh collection.sh
mv iso10303-output ${f}_output
cd ..
````

Now, in the output directory of stepmod, we specify  where the resources specific to each collection should be copied to for compilation, and that can be a different folder for each collection. This is a separate folder to the output directory where the Metanorma collection is output to.

I propose that collection.sh should be updated, to make the output directory for the Metanorma collection be not ./iso-10303-output, but {stepmod output directory}/output. That way, the output directories for each run can be kept separate and bundled together.

So if I run java -Xss5m -jar $STEPMOD2MN publication_index.xml --output $OUTPUT

then inside the collection.sh file that stepmod2mn generates, I would like to see not

bundle exec metanorma collection collection.yml -x xml,html,presentation -w iso10303-output -c cover.html

but 

bundle exec metanorma collection collection.yml -x xml,html,presentation -w $OUTPUT/output -c cover.html

So that each time I run stepmod on a publication index, I can get the output directory in a different location.

I think you can make the case that collection.yml and cover.html should also be localised to $OUTPUT, but they are regenerated on each run, and overwriting them is not a big deal. Overwriting the output of a previous collection generation OTOH is a big deal.

@ronaldtse any objection? The output directory for collections could be specified as a separate parameter to stepmod2mn, but I don't think that is necessary.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.25.

**Comment by opoudjis** [comment]
I'm keeping open because of all the confusion around the source of the templates, I will close once that is resolved and I regenerate.

**Comment by opoudjis** [comment]
Outputs folder is where I asked it to be, templates are now standalone repo.
